"use client";
import React from "react";
import { useState } from "react";
import Image from "next/image";
import Head from "next/head";
import web1 from "../../public/web1.png";
import web2 from "../../public/web2.png";
import web3 from "../../public/web3.png";
import web4 from "../../public/web4.png";
import web5 from "../../public/web5.png";
import web6 from "../../public/web6.png";
import "../styles/main.scss";

import Header from "../components/Header";
import HeroSection from "../components/HeroSection";
import Service from "@/components/Service";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={`dark ${darkMode ? "dark" : ""}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../favicon.ico" />
      </Head>
      <main className={`main ${darkMode ? "dark" : ""}`}>
        <section className="section-1">
          <Header darkMode={darkMode} setDarkMode={setDarkMode} />
          <HeroSection darkMode={darkMode} />
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 text-black dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for
              <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design, programming, and teaching.
            </p>
          </div>
          <Service darkMode={darkMode} />
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for
              <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design, programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {[web1, web2, web3, web4, web5, web6].map((image, index) => (
              <div key={index} className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={image}
                  alt=""
                />
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
